### ISSUE TITLE
Optional Parameters undefined

### ISSUE THREAD

**Issue by onehorsetown** [RasCarlito/url-composer#2]
Running this example with optional parameters, directly from your documentation does not give the expected result:

https://runkit.com/58cfd4faeebbe40014de7998/58cfd5f6e5a210001305b888

actual -> "/users/42/edit/undefined"
expected -> "/users/42/"

**Comment by RasCarlito** [comment]
Thanks @onehorsetown for pointing that out ! I'll check into it asap :)

**Comment by RasCarlito** [comment]
@onehorsetown Just released a new version (1.12.0) with the bug fix

**Comment by onehorsetown** [comment]
That did it.  Thanks!
